version: "3.9"
services:
  redis:
    networks: 
    - frontend
    image: redis:latest
    container_name: cache
    expose:
      - 6379

  postgres:
    image: postgres:10.4 
    container_name: mon-postgres
    networks: 
    - backend
    ports: 
      - "35432:5432"
    environment: 
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db
      POSTGRES_POST: 5432
    volumes: 
      - db-data:/var/lib/postgresql/data

  app:
    build: ./app
    volumes:
      - ./app:/usr/src/app
    ports:
      - 3000:3000
    networks: 
    - frontend
    depends_on:
      - redis
    environment:
      - NODE_ENV=development
      - PORT=3000
      - REDIS_URL=redis://cache
    command: "npm start"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  backend-app:
    build: ./backend
    volumes:
      - ./backend:/usr/src/backend
    ports:
      - 5000:5000
    networks: 
    - frontend
    - backend
    depends_on:
      - redis
      - postgres
    environment:
      - NODE_ENV=development
      - PORT=5000
      - REDIS_URL=redis://cache
    command: "npm start"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

networks:
  frontend:
  backend:

volumes:
  db-data: